$primaryKey = Get-AzSearchAdminKeyPair -ResourceGroupName "#{Azure.Search.ResourceGroupName}" -ServiceName "#{Azure.Search.InstanceName}" | Select-Object -ExpandProperty Primary
$queryKey = Get-AzSearchQueryKey -ResourceGroupName "#{Azure.Search.ResourceGroupName}" -ServiceName "#{Azure.Search.InstanceName}" | Select-Object -ExpandProperty Key
#Update the Octopus Global Params with the apiKeys.

$headers = @{
    "api-key" = $primaryKey
    "Content-Type" = "application/json"
}
$uri = 'https://#{Azure.Search.InstanceName}.search.windows.net/indexes/#{Azure.Search.Collection1IndexName}?api-version=2019-05-06'
$body = '{
  "name": "#{Azure.Search.Collection1IndexName}",
  "fields": [
    {
      "name": "doc_id",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": true,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "analyzer": "DocIdAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "LastIndexed",
      "type": "Edm.DateTimeOffset",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "DocumentType",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "OwnerOrgID",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ParentOrgID",
      "type": "Collection(Edm.Int32)",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "Deleted",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "DeletedDate",
      "type": "Edm.DateTimeOffset",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ApplicantID",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": false,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ApplicantFirstName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "indexAnalyzer": "WCFrontEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCFrontEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ApplicantMiddleName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "indexAnalyzer": "WCFrontEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCFrontEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ApplicantLastName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "indexAnalyzer": "WCFrontEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCFrontEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ApplicantNickName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "indexAnalyzer": "WCFrontEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCFrontEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "Suffix",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "LowerCaseAnalyzer",
      "searchAnalyzer": "LowerCaseAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CoApplicantFirstName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "indexAnalyzer": "LowerCaseAnalyzer",
      "searchAnalyzer": "LowerCaseAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CoApplicantMiddleName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "indexAnalyzer": "LowerCaseAnalyzer",
      "searchAnalyzer": "LowerCaseAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CoApplicantLastName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "indexAnalyzer": "LowerCaseAnalyzer",
      "searchAnalyzer": "LowerCaseAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CoApplicantNickName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "indexAnalyzer": "WCFrontEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCFrontEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CoApplicantFullName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "indexAnalyzer": "WCFrontEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCFrontEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CoApplicantEmail",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "EmailIndexAnalyzer",
      "searchAnalyzer": "EmailQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CoApplicantAlternateEmail",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "EmailIndexAnalyzer",
      "searchAnalyzer": "EmailQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CoApplicantHomePhone",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "PhoneGroupedIndexAnalyzer",
      "searchAnalyzer": "PhoneGroupedQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CoApplicantCellPhone",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "PhoneGroupedIndexAnalyzer",
      "searchAnalyzer": "PhoneGroupedQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CoApplicantWorkPhone",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "PhoneGroupedIndexAnalyzer",
      "searchAnalyzer": "PhoneGroupedQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CoApplicantFax",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "PhoneGroupedIndexAnalyzer",
      "searchAnalyzer": "PhoneGroupedQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ApplicantHomePhone",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "PhoneGroupedIndexAnalyzer",
      "searchAnalyzer": "PhoneGroupedQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ApplicantCellPhone",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "PhoneGroupedIndexAnalyzer",
      "searchAnalyzer": "PhoneGroupedQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ApplicantWorkPhone",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "PhoneGroupedIndexAnalyzer",
      "searchAnalyzer": "PhoneGroupedQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ApplicantFax",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "PhoneGroupedIndexAnalyzer",
      "searchAnalyzer": "PhoneGroupedQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ApplicantBusinessPhone",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "PhoneGroupedIndexAnalyzer",
      "searchAnalyzer": "PhoneGroupedQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ApplicantBusinessFax",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "PhoneGroupedIndexAnalyzer",
      "searchAnalyzer": "PhoneGroupedQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ApplicantType",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "LeadStatus",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "LeadSource",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "MaritalStatus",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "Gender",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "Description",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "Email",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "EmailIndexAnalyzer",
      "searchAnalyzer": "EmailQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "AlternateEmail",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "EmailIndexAnalyzer",
      "searchAnalyzer": "EmailQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "AllowClientCenterLoginForCoApplicant",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": false,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CoApplicantID",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "PolicyNumbers",
      "type": "Collection(Edm.String)",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": true,
      "indexAnalyzer": "LCBothEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "LCBothEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "PolicyMasterIDs",
      "type": "Collection(Edm.Int32)",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "AccountName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "WCFrontEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCFrontEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "OriginationDate",
      "type": "Edm.DateTimeOffset",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ContactNames",
      "type": "Collection(Edm.String)",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": true,
      "indexAnalyzer": "WCFrontEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCFrontEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ContactEmailAddresses",
      "type": "Collection(Edm.String)",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": true,
      "indexAnalyzer": "EmailIndexAnalyzer",
      "searchAnalyzer": "EmailQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ContactInfo",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "WCFrontEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCFrontEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "IsContact",
      "type": "Edm.Boolean",
      "facetable": true,
      "filterable": true,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "InsuredName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "PolicyAddress_edge_ngram",
      "type": "Collection(Edm.String)",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "LCBothEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "LCBothEdgeNgramIndexAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "PolicyStatusIDs",
      "type": "Collection(Edm.Int32)",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "BusinessPhone",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "WCPhoneAnalyzer",
      "searchAnalyzer": "WCPhoneAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "BusinessEmail",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "EmailIndexAnalyzer",
      "searchAnalyzer": "EmailQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CompanyName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "AlphanumericIndexAnalyzer",
      "searchAnalyzer": "AlphanumericQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "IsCommercial",
      "type": "Edm.Boolean",
      "facetable": true,
      "filterable": true,
      "retrievable": true,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "AssignedUserID",
      "type": "Edm.Int32",
      "facetable": true,
      "filterable": true,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "AssignedUserName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "LowerCaseAnalyzer",
      "searchAnalyzer": "LowerCaseAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "AssignedFirstName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "WCFrontEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCFrontEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "AssignedLastName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "WCFrontEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCFrontEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "Created",
      "type": "Edm.DateTimeOffset",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CreatedBy",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "LastModified",
      "type": "Edm.DateTimeOffset",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "LastModifiedBy",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CreatedByName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "LastModifiedByName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "AddressIDs",
      "type": "Collection(Edm.Int32)",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "FullAddress",
      "type": "Collection(Edm.String)",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": true,
      "indexAnalyzer": "LCBothEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "LCBothEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "AddressLine1",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": true,
      "indexAnalyzer": "AlphanumericIndexAnalyzer",
      "searchAnalyzer": "AlphanumericQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "AddressLine2",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": true,
      "indexAnalyzer": "LowerCaseAnalyzer",
      "searchAnalyzer": "LowerCaseAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "UnitNumber",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "City",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": true,
      "indexAnalyzer": "WCFrontEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCFrontEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "StateCode",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": true,
      "indexAnalyzer": "LowerCaseAnalyzer",
      "searchAnalyzer": "LowerCaseAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "StateName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": true,
      "indexAnalyzer": "LowerCaseAnalyzer",
      "searchAnalyzer": "LowerCaseAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ZipCode",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": true,
      "indexAnalyzer": "WCFrontEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCFrontEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "County",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "PhoneNumber",
      "type": "Collection(Edm.String)",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": true,
      "indexAnalyzer": "WCBothEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCBothEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "Name",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "indexAnalyzer": "LCBothEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "LCBothEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "FirstName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "indexAnalyzer": "WCFrontEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCFrontEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "LastName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "indexAnalyzer": "WCFrontEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCFrontEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "MiddleName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "indexAnalyzer": "WCFrontEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCFrontEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "TypeID",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "PolicyMasterID",
      "type": "Edm.Int32",
      "facetable": true,
      "filterable": true,
      "retrievable": true,
      "searchable": false,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CarrierName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "indexAnalyzer": "LowerCaseAnalyzer",
      "searchAnalyzer": "LowerCaseAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CarrierID",
      "type": "Edm.Int32",
      "facetable": true,
      "filterable": true,
      "retrievable": true,
      "searchable": false,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ShortPolicyNumber",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "indexAnalyzer": "LowerCaseAnalyzer",
      "searchAnalyzer": "LowerCaseAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "LOB",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "LOBName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "indexAnalyzer": "LowerCaseAnalyzer",
      "searchAnalyzer": "LowerCaseAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "RatingStateCode",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "indexAnalyzer": "LowerCaseAnalyzer",
      "searchAnalyzer": "LowerCaseAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "PolicyStatusID",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "PolicyNumber",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "indexAnalyzer": "LCBothEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "LCBothEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "EffectiveDate",
      "type": "Edm.DateTimeOffset",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ExpirationDate",
      "type": "Edm.DateTimeOffset",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "BillingCompany",
      "type": "Edm.Int32",
      "facetable": true,
      "filterable": true,
      "retrievable": true,
      "searchable": false,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "SourceTypeID",
      "type": "Edm.Int32",
      "facetable": true,
      "filterable": true,
      "retrievable": true,
      "searchable": false,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "StatusID",
      "type": "Edm.Int32",
      "facetable": true,
      "filterable": true,
      "retrievable": true,
      "searchable": false,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ProducerCode",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "indexAnalyzer": "LowerCaseAnalyzer",
      "searchAnalyzer": "LowerCaseAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "Premium",
      "type": "Edm.Double",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CancellationDate",
      "type": "Edm.DateTimeOffset",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "AnnualizedPremium",
      "type": "Edm.Double",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "BillingType",
      "type": "Edm.Int32",
      "facetable": true,
      "filterable": true,
      "retrievable": true,
      "searchable": false,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "PolicyTransactionType",
      "type": "Edm.Int32",
      "facetable": true,
      "filterable": true,
      "retrievable": true,
      "searchable": false,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "PolicyTransactionTypeName",
      "type": "Edm.String",
      "facetable": true,
      "filterable": true,
      "retrievable": true,
      "searchable": false,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "PolicyTransactionEffectiveDate",
      "type": "Edm.DateTimeOffset",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "PriorPolicyNumbers",
      "type": "Collection(Edm.String)",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": true,
      "indexAnalyzer": "WCBothEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCBothEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ShareWithCustomer",
      "type": "Edm.Boolean",
      "facetable": true,
      "filterable": true,
      "retrievable": true,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ApplicantListID",
      "type": "Edm.Int32",
      "facetable": true,
      "filterable": true,
      "retrievable": true,
      "searchable": false,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "IncludedApplicantIDs",
      "type": "Collection(Edm.Int32)",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ExcludedApplicantIDs",
      "type": "Collection(Edm.Int32)",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "IncludedApplicantCount",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ExcludedApplicantCount",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ApplicantCriteriaFlags",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "LastModifiedMembers",
      "type": "Edm.DateTimeOffset",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
	{
      "name": "ListTypeID",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "ContactID",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "OrganizationID",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "VendorID",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "IsVIPCustomer",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "IsBankingCustomer",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "IsBillingCustomer",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "UserID",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "UserName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "indexAnalyzer": "LCBothEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "LCBothEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "OwnerOrgName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "OwnerOrgCityName",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "OwnerOrgStateCode",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "InvoiceID",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "InvoiceNumber",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": true,
      "indexAnalyzer": "WCBothEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCBothEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "InvoiceStatus",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "InvoiceDate",
      "type": "Edm.DateTimeOffset",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "InvoiceAmount",
      "type": "Edm.Double",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "InvoiceType",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "InvoiceAction",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CertificateMasterID",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CertificateMasterPolicyEffectiveDate",
      "type": "Edm.DateTimeOffset",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CertificateMasterPolicyExpirationDate",
      "type": "Edm.DateTimeOffset",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "sortable": false,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CertificateMasterName_edge_ngram",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": true,
      "indexAnalyzer": "WCBothEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCBothEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CertificateMasterAcordFormName_edge_ngram",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": true,
      "indexAnalyzer": "WCBothEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCBothEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CertificateMasterPolicyNumbers_edge_ngram",
      "type": "Collection(Edm.String)",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": true,
      "indexAnalyzer": "LCBothEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "LCBothEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CertificateMasterPolicyLOBs_edge_ngram",
      "type": "Collection(Edm.String)",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "searchable": true,
      "indexAnalyzer": "LCBothEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "LCBothEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CertificateHolderID",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CertificateHolderMobileNumber_edge_ngram",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "PhoneGroupedIndexAnalyzer",
      "searchAnalyzer": "PhoneGroupedQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CertificateHolderFaxNumber_edge_ngram",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "PhoneGroupedIndexAnalyzer",
      "searchAnalyzer": "PhoneGroupedQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CertificateHolderEntryTypeID",
      "type": "Edm.Int32",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": false,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "CertificateHolderName_edge_ngram",
      "type": "Edm.String",
      "facetable": false,
      "filterable": true,
      "key": false,
      "retrievable": true,
      "searchable": true,
      "sortable": false,
      "indexAnalyzer": "WCBothEdgeNgramIndexAnalyzer",
      "searchAnalyzer": "WCBothEdgeNgramQueryAnalyzer",
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "IsShared",
      "type": "Edm.Int32",
      "facetable": true,
      "filterable": true,
      "retrievable": true,
      "sortable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    },
    {
      "name": "OpportunityIDs",
      "type": "Collection(Edm.Int32)",
      "facetable": false,
      "filterable": true,
      "retrievable": true,
      "analyzer": null,
      "indexAnalyzer": null,
      "searchAnalyzer": null,
      "synonymMaps": [],
      "fields": []
    }
  ],
  "suggesters": [],
  "scoringProfiles": [
    {
      "name": "freshness",
      "text": {
        "weights": {
          "ApplicantLastName": 5,
          "ApplicantFirstName": 3,
          "ApplicantNickName": 2,
          "CompanyName": 5,
          "CoApplicantNickName": 2,
          "AccountName": 7
        }
      },
      "functions": [
        {
          "type": "freshness",
          "fieldName": "LastIndexed",
          "boost": 10,
          "interpolation": "quadratic",
          "freshness": {
            "boostingDuration": "P365D"
          }
        }
      ]
    }
  ],
  "defaultScoringProfile": "freshness",
  "corsOptions": {
    "allowedOrigins": [ "*" ],
    "maxAgeInSeconds": null
  },
  "analyzers": [
    {
      "@odata.type": "#Microsoft.Azure.Search.CustomAnalyzer",
      "name": "LowerCaseAnalyzer",
      "tokenizer": "keyword_v2",
      "tokenFilters": [
        "lowercase"
      ],
      "charFilters": []
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.CustomAnalyzer",
      "name": "EmailExactAnalyzer",
      "tokenizer": "keyword_v2",
      "tokenFilters": [
        "trim",
        "lowercase"
      ],
      "charFilters": []
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.CustomAnalyzer",
      "name": "PhoneExactIndexAnalyzer",
      "tokenizer": "keyword_v2",
      "tokenFilters": [
        "trim"
      ],
      "charFilters": [
        "PhonePatternReplaceFilter"
      ]
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.CustomAnalyzer",
      "name": "PhoneExactQueryAnalyzer",
      "tokenizer": "keyword_v2",
      "tokenFilters": [
        "trim"
      ],
      "charFilters": []
    },
	{
      "@odata.type": "#Microsoft.Azure.Search.CustomAnalyzer",
      "name": "DocIdAnalyzer",
      "tokenizer": "keyword_v2",
      "tokenFilters": [
        "trim"
      ],
      "charFilters": ["DocIdPatternReplaceIndexFilter"]
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.CustomAnalyzer",
      "name": "PhoneGroupedQueryAnalyzer",
      "tokenizer": "keyword_v2",
      "tokenFilters": [],
      "charFilters": [ "PhonePatternReplaceQueryFilter1", "PhonePatternReplaceQueryFilter2" ]
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.CustomAnalyzer",
      "name": "PhoneGroupedIndexAnalyzer",
      "tokenizer": "keyword_v2",
      "tokenFilters": [ "PhoneGroupCapturePatternReplaceIndexFilter" ],
      "charFilters": [ "PhonePatternReplaceIndexFilter1", "PhonePatternReplaceIndexFilter2" ]
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.CustomAnalyzer",
      "name": "WCPhoneAnalyzer",
      "tokenizer": "keyword_v2",
      "tokenFilters": [],
      "charFilters": [ "PhonePatternReplaceIndexFilter1", "PhonePatternReplaceIndexFilter2" ]
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.CustomAnalyzer",
      "name": "AlphanumericIndexAnalyzer",
      "tokenizer": "whitespace",
      "tokenFilters": [ "lowercase", "front_filter_30" ],
      "charFilters": [ "AlphanumericPatternReplaceFilter" ]
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.CustomAnalyzer",
      "name": "AlphanumericQueryAnalyzer",
      "tokenizer": "whitespace",
      "tokenFilters": [ "lowercase" ],
      "charFilters": [ "AlphanumericPatternReplaceFilter" ]
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.CustomAnalyzer",
      "name": "EmailQueryAnalyzer",
      "tokenizer": "keyword_v2",
      "tokenFilters": [ "lowercase" ],
      "charFilters": []
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.CustomAnalyzer",
      "name": "EmailIndexAnalyzer",
      "tokenizer": "keyword_v2",
      "tokenFilters": [ "lowercase", "front_filter" ],
      "charFilters": []
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.CustomAnalyzer",
      "name": "LCBothEdgeNgramIndexAnalyzer",
      "tokenizer": "whitespace",
      "tokenFilters": [ "lowercase", "front_filter_40", "reverse", "front_filter_40", "reverse" ],
      "charFilters": [ "BothEdgeCharFilter" ]
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.CustomAnalyzer",
      "name": "LCBothEdgeNgramQueryAnalyzer",
      "tokenizer": "whitespace",
      "tokenFilters": [ "lowercase" ],
      "charFilters": [ "BothEdgeCharFilter" ]
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.CustomAnalyzer",
      "name": "WCBothEdgeNgramQueryAnalyzer",
      "tokenizer": "whitespace",
      "tokenFilters": [ "lowercase" ],
      "charFilters": []
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.CustomAnalyzer",
      "name": "WCBothEdgeNgramIndexAnalyzer",
      "tokenizer": "whitespace",
      "tokenFilters": [ "lowercase", "front_filter_40", "reverse", "front_filter_40", "reverse" ],
      "charFilters": []
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.CustomAnalyzer",
      "name": "WCFrontEdgeNgramIndexAnalyzer",
      "tokenizer": "whitespace",
      "tokenFilters": [ "lowercase", "front_filter_20" ],
      "charFilters": []
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.CustomAnalyzer",
      "name": "WCFrontEdgeNgramQueryAnalyzer",
      "tokenizer": "whitespace",
      "tokenFilters": [ "lowercase" ],
      "charFilters": []
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.CustomAnalyzer",
      "name": "TextGeneralAnalyzer",
      "tokenizer": "whitespace",
      "tokenFilters": [ "lowercase" ],
      "charFilters": []
    }
  ],
  "charFilters": [
    {
      "@odata.type": "#Microsoft.Azure.Search.PatternReplaceCharFilter",
      "name": "BothEdgeCharFilter",
      "pattern": "([^0-9a-zA-Z\\s])",
      "replacement": ""
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.PatternReplaceCharFilter",
      "name": "AlphanumericPatternReplaceFilter",
      "pattern": "([^0-9a-zA-Z&amp; ])",
      "replacement": " "
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.PatternReplaceCharFilter",
      "name": "PatternReplaceFilter",
      "pattern": "([^\\da-zA-Z])",
      "replacement": " "
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.PatternReplaceCharFilter",
      "name": "PhonePatternReplaceFilter",
      "pattern": "([^0-9])",
      "replacement": ""
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.PatternReplaceCharFilter",
      "name": "PhonePatternReplaceIndexFilter1",
      "pattern": "([^\\d])",
      "replacement": ""
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.PatternReplaceCharFilter",
      "name": "PhonePatternReplaceIndexFilter2",
      "pattern": "(\\d*)(\\d{10}$)",
      "replacement": "$2"
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.PatternReplaceCharFilter",
      "name": "PhonePatternReplaceQueryFilter1",
      "pattern": "([^0-9a-zA-Z])",
      "replacement": ""
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.PatternReplaceCharFilter",
      "name": "PhonePatternReplaceQueryFilter2",
      "pattern": "([0-9a-zA-Z]*)([0-9a-zA-Z]{10}$)",
      "replacement": "$2"
    },
	{
      "@odata.type": "#Microsoft.Azure.Search.PatternReplaceCharFilter",
      "name": "DocIdPatternReplaceIndexFilter",
      "pattern": "([^0-9])",
      "replacement": ""
    }
  ],
  "tokenFilters": [
    {
      "@odata.type": "#Microsoft.Azure.Search.PatternCaptureTokenFilter",
      "name": "PhoneGroupCapturePatternReplaceIndexFilter",
      "patterns": [ "(\\d{3})((\\d{3})(\\d{4}))" ],
      "preserveOriginal": "true"
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.EdgeNGramTokenFilterV2",
      "name": "front_filter_20",
      "minGram": 1,
      "maxGram": 20,
      "side": "front"
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.EdgeNGramTokenFilterV2",
      "name": "front_filter_30",
      "minGram": 1,
      "maxGram": 30,
      "side": "front"
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.EdgeNGramTokenFilterV2",
      "name": "front_filter_40",
      "minGram": 1,
      "maxGram": 40,
      "side": "front"
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.EdgeNGramTokenFilterV2",
      "name": "front_filter",
      "minGram": 1,
      "maxGram": 100,
      "side": "front"
    },
    {
      "@odata.type": "#Microsoft.Azure.Search.EdgeNGramTokenFilterV2",
      "name": "back_filter",
      "minGram": 1,
      "maxGram": 100,
      "side": "back"
    }
  ],
  "tokenizers": [],
  "@odata.etag": "\"0x8D74DC882EA7053\""
}'

Invoke-RestMethod -Uri $uri -Method Put -Headers $headers -Body $body 